---
- name: Test AWS Credentials
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/aws_credentials.yaml  # Poprawiona ścieżka do pliku YAML

  tasks:
    - name: Ping AWS
      uri:
        url: "https://sts.{{ region }}.amazonaws.com/"
        method: GET
        headers:
          Authorization: "AWS {{ aws_access_key }}:{{ aws_secret_key }}"
        validate_certs: yes
      register: aws_ping_result

    - debug:
        msg: "AWS Ping successful!"
      when: aws_ping_result.status == 200
